### ISSUE TITLE
自定义图片不生效

### ISSUE THREAD

**Issue by Finn9** [andersonaddo/allsearch#2]
我尝试了几个图片网站和图床的链接，自定义图片之后背景都变成了黑色，是不是图片链接有什么特殊要求？！谢谢大佬

**Comment by andersonaddo** [comment]
这是由于图像 URL 的 CORS 问题。
我稍后会尝试找到解决方法，但我现在有点忙！

**Comment by Finn9** [comment]
好的，非常感谢

**Comment by andersonaddo** [comment]
我修好了它！
对不起，我花了这么长时间；我没有忘记，但我还有很多其他事情要做。
尝试一些新的背景，如果它不起作用，请告诉我。
