### ISSUE TITLE
Enhancement suggestion: keyboard shortcut for locating the focus on the searchbox

### ISSUE THREAD

**Issue by whyXVI** [andersonaddo/allsearch#3]
Same as title

**Comment by andersonaddo** [comment]
Hiya!

You know the search bar of the main page autofocuses when you first load the page? Does that not work for you?

I'm just wondering what's the use case scenario you're facing thats making you ask for this. 

One thing I can imagine is that you're visiting the same Allsearch tab more than once the single autofocus on load isn't enough. Is that the case?

Happy to implement some changes, just want to understand what doing on a little more.

**Comment by whyXVI** [comment]
Sure, that's my case. I maintain one main page while browsing. When I go back to it, I find it troublesome to navigate to the searchBox using tabs.

Another chance is that, when we enable a firefox add-on which overrides new tabs by creating a new homepage, there will be a blank and focused URL bar. But maybe this issue couldn't be solved because it's browser level behaviour.

If you could implement an extra feature I would be really glad. It's cool as well isn't it?

**Comment by andersonaddo** [comment]
Sure thing. I'll implement that for you soon then and let you know!

**Comment by andersonaddo** [comment]
All done!
Command + G (Or Ctrl + G)
